/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sequence_gate_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(962c799d991ae1f949c5927de5db4299)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <corrsounder/sequence_gate_cc.h>
// pydoc.h is automatically generated in the build directory
#include <sequence_gate_cc_pydoc.h>

void bind_sequence_gate_cc(py::module& m)
{

    using sequence_gate_cc    = gr::corrsounder::sequence_gate_cc;


    py::class_<sequence_gate_cc,
        std::shared_ptr<sequence_gate_cc>>(m, "sequence_gate_cc", D(sequence_gate_cc))

        .def(py::init(&sequence_gate_cc::make),
           py::arg("sequence_length"),
           py::arg("sample_rate") = 1.0,
           D(sequence_gate_cc,make)
        )
        



        ;




}








